---
title: "Orthanc"
description: "dicom server open source"
author: "BenKorea"
date: "2025-02-26"
date-modified: last-modified
categories: [dicom server, Orthanc]
---

벨기에에서 개발한 오픈소스이다.
Restful APT를 지원하기 때문에 DICOM query, retrieve, send, move 등을 쉽게 구현할 수 있으리라는기대감으로 설치하여 향후의 시스템을 모사하여 개발을 진행하고 있다.

### 완전제거방법

구동이 제대로 되지 않을 때가 많아서 완전제거방법을 조사하니 아래와 같았다.

1.  서비스 관리자에서 "Orthanc" 서비스를 찾아 중지합니다.

2.  C:\\Program Files\\Orthanc 폴더를 삭제합니다.

3.  C:\\Users\\\<username\>\\AppData\\Local\\Orthanc 폴더를 삭제합니다.

4.  Orthanc 설정 레지스트리 삭제 (Windows만 해당):

    1.  regedit를 실행합니다.

    2.  HKEY_LOCAL_MACHINE\\SOFTWARE\\Orthanc 키를 삭제합니다.

5.  제어판에서 "프로그램 제거"를 선택하고 "Orthanc"를 제거합니다.


### 설치파일

공식사이트 https://orthanc.uclouvain.be/downloads/windows-64/installers/index.html 
2025년 2월 27일 release된 25.2.0 버전이 최신이다.

### 설치폴더
기본설치폴더는 C:\\Program Files\\Orthanc Server이며 data는 C:\\Orthanc에 기본 설치된다. 이를 변경하면 Plugins에서 설치경로 인식의 문제 등으로 실행에 문제가 발생하는 것 같으므로 기본설치폴더에 설치하는 것이 좋겠다.

### 설정파일
main 설정파일은 C:\\Program Files\\Orthanc Server\\Configuration\\orthanc.json이다. 

### DICOMModality 설정
매뉴얼(https://orthanc.uclouvain.be/book/integrations/modality.html#configure-modality)의 예시는 아래와 같았다.

```r
// The list of the known DICOM modalities
"DicomModalities" : {
  "echo1" : [ "ECHO1", "123.124.125.10", 104 ]
},
```

위를 참고하여 개발시스템의 DicomModality를 아래와 같이 설정하였다.
```r
  "NMDOSE" : [ "NMDOSE", "127.0.0.1", 5678 ],
  "NMIQ" : [ "NMIQ", "127.0.0.1", 5679 ],
  "NMFULLDATA" : [ "NMFULLDATA", "127.0.0.1", 5680 ],
  "NMTEMPSERVER" : [ "NMTEMPSERVER", "127.0.0.1", 5681 ],
  "ZETTAPACS" : [ "ZETTAPACS", "127.0.0.1", 5682 ],
  "SLICER" : [ "SLICER", "127.0.0.1", 11112 ]
```

configuration을 설정하는 동안에 Orthanc를 완전히 중지하였다가 수정 후 service를 재개하여야 수정사항이 반영됨을 주의해야 한다.
그리고 쓰기권한이 제한된 경우에는 이를 해결해야 한다.

### Port
- 4242

### HPPT port
- 8042

### 설정
- PostgreSQL로 DICOM metadata를 저장하기 위해서 postgresql.json을 아래와 같이 설정하였다.

```json
{
  "PostgreSQL" : {
    "EnableIndex" : true,
    "EnableStorage" : false,               // You likely don't need to enable this option
    "Host" : "localhost",
    "Port" : 5432,
    "Database" : "orthanc",
    "Username" : "nmuser",
    "Password" : "iloveben",
    "Lock" : true,
    "EnableSsl" : false,                   // New in release 3.0
    "MaximumConnectionRetries" : 10,       // New in release 3.0
    "ConnectionRetryInterval" : 5,         // New in release 3.0
    "IndexConnectionsCount" : 50,          // New in release 4.0 - new default value in 7.0
    "TransactionMode": "ReadCommitted",    // New in release 6.0 - new default value in 7.0
    "EnableVerboseLogs": false,            // New in release 6.0
    "HousekeepingInterval": 1,             // New in release 7.0
    "AllowInconsistentChildCounts": false  // New in release 7.2
  }
}
```

### Retrieve 자동화
Orthanc에 내장된 Lua engine으로 특정기간동안의 Modality=="PT"인 경우를 retrieve하도록 다음의 단계를 진행하였다.
- orthanc.json에서 Lua script를 아래와 같이 활성화하였다.
```orthanc.json
"LuaScripts" : [C:\\Orthanc\\lua\\retrieve_nm_studies.lua"],
```

그러나 query 요청에 실패해 일단 보류

```curl
curl -X POST http://localhost:8042/tools/execute-script --data-binary "OnTimer()"
```
