---
title: "DICOM 서버"
description: "개발기록"
author: "BenKorea"
date: "2025-02-26"
date-modified: last-modified
categories: [dicom server]
---


### 구축 필요성

개발 단계에서 실제 PACS를 모사할 수 있는 별도의 DICOM 서버를 구축할 필요가 아래와 같은 오픈소스들을 검토하였다.

### Conquest dicom server

설정과 사용법이 간단하여 저자가 테스트에 가장 먼저 성공한 프로그램이기도 하다. 특히 저장폴더가 직관적이다.

#### 설치파일
최신 설치파일은 공식사이트가 아닌 Cnquest User Forum에 공개된 2024년 9월 25일 release된 버전 1.5.0e (dicomserver-1.5.0e.zip, https://forum.iq-image.com/forum/index.php?thread/50654-conquest-1-5-0e-released/)가 최신이다.

#### 설치방법
설치방법은 원하는 폴더에서 설치파일의 압축을 풀면된다.
업그레이드시에는 매뉴얼에 따르면 다음의 지시를 따르면 된다.
- 기본적으로 exe 및 dll 파일을 교체하면 업데이트 가능하지만, 
- 일부 설정 파일(dicom.sql, dgatesop.lst, dicom.ini)을 조정할 경우 데이터베이스를 다시 생성해야 할 수도 있습니다.
- 서버는 반드시 업데이트 전에 중지해야 하며, 서비스로 실행 중이면 제어판에서 중지 또는 서비스 해제가 필요합니다.
- 데이터베이스 재생성이 필요한 경우 매우 오랜 시간이 걸릴 수 있으므로 주의해야 합니다.
- 기존 데이터를 유지하려면 dicom.sql을 백업 후 복원하는 것이 좋습니다.
- 저자의 경우는 data폴더, acrnema.map, dicom.ini 파일을 제외하고 삭제한 뒤 설치압축파일을 풀면 데이터와 설정이 유지된 체로 업그레이드 하고 database reganeration을 하였다.

#### 활용 현황
이 서버프로그램으로 저자는 NMDose, NMIQ, NMFullData, NMTEMPSERVER, ZettaPACS를 구축하여 선량분석시스템, 영상품질자동화, clinical PACS모사, 임시서버, clinical PACS 모사의 목적으로 사용하고 있다.

#### Lua script
쿼리를 정교하게 할 수 있다.

#### 저장파일의 이름을 지정하는 방식
%id_%studydate\%modality_%series_%sopuid.dcm



### Orthanc DICOM Server
벨기에에서 개발한 오픈소스이다.
Restful APT를 지원하기 때문에 DICOM query, retrieve, send, move 등을 쉽게 구현할 수 있으리라는기대감으로 설치하여 향후의 시스템을 모사하여 개발을 진행하고 있다.

#### 설치파일
2025년 2월 27일 release된 25.2.0 버전이 최신이다.
https://orthanc.uclouvain.be/downloads/windows-64/installers/index.html
저자는 C:\\Program Files\\ 폴더보다는 C:\\를 선호하여 C:\\Orthanc에 설치하였다.

#### 주의사항
설치이후 처음 실행시에 설치폴더의 Orthanc.exe를 먼저 실핼시키고 방화벽을 해제한 후 explorer를 실행해야 하는 것 같다.

#### 장단점
Orthanc은 웹 기반 DICOM 관리 및 AI 분석, 클라우드 통합이 필요한 경우 유리하다고 한다.
Conquest DICOM Server는 빠른 속도의 로컬 PACS, 대량의 DICOM 데이터 처리, **자동화된 스크립팅 (Lua)**이 필요한 경우 적합하다고 한다.

#### 설정
.Configuration\\orthanc.json을 notepad 등으로 수정하며 default 값으로 진행하였다.

  // HTTP port for the REST services and for the GUI
  "HttpPort" : 8042,
  
  // The DICOM Application Entity Title (cannot be longer than 16
  // characters)
  "DicomAet" : "ORTHANC",  
  
  // The DICOM port
  "DicomPort" : 4242,
  
  // The default encoding that is assumed for DICOM files without
  // "SpecificCharacterSet" DICOM tag, and that is used when answering
  // C-FIND requests (including worklists). The allowed values are
  // "Ascii", "Utf8", "Latin1", "Latin2", "Latin3", "Latin4",
  // "Latin5", "Cyrillic", "Windows1251", "Arabic", "Greek", "Hebrew",
  // "Thai", "Japanese", "Chinese", "JapaneseKanji", "Korean", and
  // "SimplifiedChinese".
  "DefaultEncoding" : "Latin1",
  
  // The list of the known DICOM modalities. This option is ignored if
  // "DicomModalitiesInDatabase" is set to "true", in which case you
  // must use the REST API to define modalities.
  "DicomModalities" : {
     "NMDOSE" : [ "NMDOSE", "127.0.0.1", 5678 ],
     "NMIQ" : [ "NMIQ", "127.0.0.1", 5679 ],
     "NMFULLDATA" : [ "NMFULLDATA", "127.0.0.1", 5680 ],
     "NMTEMPSERVER" : [ "NMTEMPSERVER", "127.0.0.1", 5681 ],
     "ZETTAPACS" : [ "ZETTAPACS", "127.0.0.1", 5682 ],
     "SLICER" : [ "SLICER", "127.0.0.1", 11112 ]
    /**  


#### remote server






